server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service
  cloud:
    config:
         uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      
ribbon:
  eureka:
    enabled: true